#!/usr/bin/env python3
"""Execute simulation plans on real UR robots.

This script replays trajectories generated by simforge_new's proto_sim mode
on physical UR robots using the RTDE protocol.

Usage:
    source .simforge/bin/activate
    python -m simforge_new.services.real_robot.run_plan \
        --robot-ip 192.168.1.9 \
        --plan simforge_new/logs/ur5e_ir_illuminator_test_plan.json \
        --velocity-scale 0.3

Features:
- Time-parameterized trajectory execution using servoJ
- Configurable velocity scaling for safety
- Supports executing specific poses or all poses in a plan
- Returns robot to home position after execution
"""

from __future__ import annotations

import argparse
import json
import logging
import math
import sys
import time
from pathlib import Path
from typing import List, Optional

from .driver import URRobotDriver, RobotDriverConfig
from .trajectory_executor import Trajectory


def setup_logging(level: str = "INFO") -> logging.Logger:
    """Configure logging."""
    logging.basicConfig(
        level=getattr(logging, level.upper()),
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%H:%M:%S",
    )
    return logging.getLogger("run_plan")


def run_plan(
    robot_ip: str,
    plan_path: str,
    velocity_scale: float = 0.5,
    object_key: Optional[str] = None,
    poses: Optional[List[str]] = None,
    use_servo: bool = True,
    inter_pose_delay: float = 1.0,
    dry_run: bool = False,
    logger: Optional[logging.Logger] = None,
) -> bool:
    """Execute a simulation plan on a real robot.
    
    Args:
        robot_ip: IP address of the UR robot.
        plan_path: Path to plan JSON file.
        velocity_scale: Velocity scaling factor (0.0 to 1.0).
        object_key: Specific object to execute (None for first object).
        poses: Specific pose keys to execute (None for all).
        use_servo: Use servoJ (True) or moveJ path (False).
        inter_pose_delay: Delay between poses in seconds.
        dry_run: If True, only show what would be executed.
        logger: Logger instance.
    
    Returns:
        True if execution successful.
    """
    logger = logger or logging.getLogger("run_plan")
    
    # Load plan
    plan_file = Path(plan_path)
    if not plan_file.exists():
        logger.error("Plan file not found: %s", plan_path)
        return False
    
    with open(plan_file) as f:
        plan_data = json.load(f)
    
    # Determine object to execute
    if object_key:
        if object_key not in plan_data:
            logger.error("Object '%s' not found in plan. Available: %s",
                        object_key, list(plan_data.keys()))
            return False
        obj_data = plan_data[object_key]
    else:
        object_key = list(plan_data.keys())[0]
        obj_data = plan_data[object_key]
        logger.info("Using first object: %s", object_key)
    
    # Get pose info
    pose_in_robot_frame = obj_data.get("pose_in_robot_frame", [])
    logger.info("Object pose in robot frame: %s", pose_in_robot_frame)
    
    # Collect poses to execute
    pose_entries = []
    for key, value in obj_data.items():
        if key == "pose_in_robot_frame":
            continue
        if not isinstance(value, dict) or "waypoints" not in value:
            continue
        if poses and key not in poses:
            continue
        pose_entries.append((key, value))
    
    # Sort by pose number
    def pose_sort_key(item):
        key = item[0]
        if key == "pose_home":
            return (1, 0)  # Home goes last
        try:
            num = int(key.replace("pose_", ""))
            return (0, num)
        except ValueError:
            return (0, 999)
    
    pose_entries.sort(key=pose_sort_key)
    
    logger.info("Found %d poses to execute", len(pose_entries))
    for key, _ in pose_entries:
        logger.info("  - %s", key)
    
    if dry_run:
        logger.info("Dry run - not executing")
        return True
    
    # Configure driver
    config = RobotDriverConfig(
        robot_ip=robot_ip,
        robot_name="ur_robot",
        robot_model="UR5e",
        max_joint_velocity=1.05,
        max_joint_acceleration=1.4,
        velocity_scaling=velocity_scale,
    )
    
    logger.info("Connecting to robot at %s...", robot_ip)
    
    with URRobotDriver(config, logger) as driver:
        if not driver.is_ready():
            logger.error("Robot not ready for motion")
            return False
        
        logger.info("Robot connected and ready")
        
        # Store initial position for return
        initial_joints = driver.get_joint_positions()
        
        successes = 0
        failures = 0
        
        for pose_key, pose_data in pose_entries:
            waypoints = pose_data["waypoints"]
            times_s = pose_data.get("times_s")
            duration = pose_data.get("duration")
            
            logger.info("=" * 50)
            logger.info("Executing %s: %d waypoints", pose_key, len(waypoints))
            
            # Scale duration by velocity
            if duration:
                scaled_duration = duration / velocity_scale
            else:
                scaled_duration = None
            
            trajectory = Trajectory.from_waypoints(waypoints, times_s, scaled_duration)
            
            logger.info("Trajectory: %.2fs duration", trajectory.total_duration)
            
            # Move to start position first
            start_joints = waypoints[0]
            logger.info("Moving to start position...")
            
            if not driver.move_to_joints(start_joints, blocking=True):
                logger.error("Failed to reach start position")
                failures += 1
                continue
            
            # Execute trajectory
            logger.info("Executing trajectory...")
            start_time = time.time()
            
            if driver.execute_trajectory(trajectory, blocking=True, use_servo=use_servo):
                elapsed = time.time() - start_time
                logger.info("✅ %s completed in %.1fs", pose_key, elapsed)
                successes += 1
            else:
                logger.error("❌ %s failed", pose_key)
                failures += 1
            
            # Inter-pose delay
            if inter_pose_delay > 0:
                time.sleep(inter_pose_delay)
        
        logger.info("=" * 50)
        logger.info("Execution complete: %d success, %d failed", successes, failures)
        
        # Return to initial position
        logger.info("Returning to initial position...")
        driver.move_to_joints(initial_joints, blocking=True)
        logger.info("Done")
    
    return failures == 0


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Execute simulation plans on real UR robots",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--robot-ip",
        required=True,
        help="IP address of the UR robot",
    )
    parser.add_argument(
        "--plan",
        required=True,
        help="Path to simulation plan JSON file",
    )
    parser.add_argument(
        "--velocity-scale",
        type=float,
        default=0.5,
        help="Velocity scaling factor 0.0-1.0 (default: 0.5)",
    )
    parser.add_argument(
        "--object",
        dest="object_key",
        help="Specific object to execute (default: first)",
    )
    parser.add_argument(
        "--poses",
        nargs="+",
        help="Specific poses to execute (e.g., pose_1 pose_2)",
    )
    parser.add_argument(
        "--use-movej",
        action="store_true",
        help="Use moveJ path instead of servoJ",
    )
    parser.add_argument(
        "--inter-pose-delay",
        type=float,
        default=1.0,
        help="Delay between poses in seconds (default: 1.0)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be executed without moving",
    )
    parser.add_argument(
        "--log-level",
        default="INFO",
        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
        help="Logging level",
    )
    
    args = parser.parse_args()
    logger = setup_logging(args.log_level)
    
    success = run_plan(
        robot_ip=args.robot_ip,
        plan_path=args.plan,
        velocity_scale=args.velocity_scale,
        object_key=args.object_key,
        poses=args.poses,
        use_servo=not args.use_movej,
        inter_pose_delay=args.inter_pose_delay,
        dry_run=args.dry_run,
        logger=logger,
    )
    
    return 0 if success else 1


if __name__ == "__main__":
    sys.exit(main())
